import { Suspense } from "react";
import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { CategoryBadge } from "@/components/category-badge";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { getArticleWithDay } from "@/lib/data/queries";
import type { Metadata } from "next";

interface ArticlePageProps {
  params: Promise<{ id: string }>;
}

// generateMetadata runs in a separate pipeline — params access is fine here.
export async function generateMetadata({
  params,
}: ArticlePageProps): Promise<Metadata> {
  const { id } = await params;
  const data = await getArticleWithDay(id);

  if (!data) return { title: "Article not found — The Alternative Times" };

  return {
    title: `${data.article.title} — The Alternative Times`,
    description: data.article.content.slice(0, 160),
  };
}

// Static shell — passes params into the Suspense boundary.
export default function ArticlePage({ params }: ArticlePageProps) {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <Suspense fallback={<ArticleSkeleton />}>
        <ArticleContent params={params} />
      </Suspense>
    </div>
  );
}

// ─── Dynamic content ──────────────────────────────────────────────────────────

async function ArticleContent({ params }: ArticlePageProps) {
  const { id } = await params;

  const data = await getArticleWithDay(id);
  if (!data) notFound();

  const { article, dayDate } = data;

  const articleDate = dayDate
    ? new Date(dayDate).toLocaleDateString("en-US", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : null;

  const dayDateParam = dayDate
    ? new Date(dayDate).toISOString().slice(0, 10)
    : null;

  const paragraphs = article.content
    .split("\n")
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <>
      <div className="mb-6">
        <Button variant="ghost" size="sm" asChild className="-ml-2">
          <Link href={dayDateParam ? `/news?date=${dayDateParam}` : "/news"}>
            ← Back to {articleDate ?? "news"}
          </Link>
        </Button>
      </div>

      {/* Hero poster */}
      {article.imageUrl && (
        <div className="relative w-full h-72 sm:h-96 rounded-xl overflow-hidden mb-8">
          <Image
            src={article.imageUrl}
            alt={article.title}
            fill
            priority
            sizes="(max-width: 768px) 100vw, 768px"
            className="object-cover"
          />
          <div className="absolute inset-0 bg-linear-to-t from-black/40 to-transparent" />
        </div>
      )}

      <article>
        <header className="mb-8">
          <div className="flex flex-wrap items-center gap-2 mb-4">
            <Badge
              variant="outline"
              className="text-amber-700 border-amber-300 bg-amber-50 text-xs"
            >
              Alternative History
            </Badge>
            {articleDate && (
              <span className="text-sm text-muted-foreground">
                {articleDate}
              </span>
            )}
          </div>

          <h1 className="font-heading text-3xl sm:text-4xl font-bold leading-tight tracking-tight mb-4">
            {article.title}
          </h1>

          <div className="flex flex-wrap items-center gap-4">
            <CategoryBadge
              category={article.category}
              region={article.region}
              importance={article.importance}
            />
            <span className="text-xs text-muted-foreground">
              Importance: {article.importance}/10
            </span>
          </div>
        </header>

        <Separator className="mb-8" />

        <div className="prose prose-stone max-w-none">
          {paragraphs.map((paragraph, i) => (
            <p
              key={i}
              className="text-base leading-8 text-foreground/90 mb-5 first-letter:text-3xl first-letter:font-heading first-letter:font-bold first-letter:float-left first-letter:mr-2 first-letter:mt-1 not-first:first-letter:text-base not-first:first-letter:font-normal not-first:first-letter:float-none not-first:first-letter:mr-0 not-first:first-letter:mt-0"
            >
              {paragraph}
            </p>
          ))}
        </div>

        <Separator className="my-8" />

        <footer className="flex flex-wrap items-center justify-between gap-4 text-xs text-muted-foreground">
          <span>
            Generated by AI · Alternative History · The Alternative Times
          </span>
          {dayDateParam && (
            <Link
              href={`/news?date=${dayDateParam}`}
              className="underline hover:text-foreground transition-colors"
            >
              More news from this day →
            </Link>
          )}
        </footer>
      </article>
    </>
  );
}

// ─── Skeleton ─────────────────────────────────────────────────────────────────

function ArticleSkeleton() {
  return (
    <>
      <Skeleton className="h-8 w-32 mb-6" />
      <div className="space-y-4 mb-8">
        <div className="flex gap-2">
          <Skeleton className="h-5 w-28 rounded-full" />
          <Skeleton className="h-5 w-36" />
        </div>
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-10 w-3/4" />
        <Skeleton className="h-5 w-24 rounded-full" />
      </div>
      <Skeleton className="h-px w-full mb-8" />
      <div className="space-y-3">
        {Array.from({ length: 6 }).map((_, i) => (
          <Skeleton key={i} className="h-5 w-full" />
        ))}
        <Skeleton className="h-5 w-2/3" />
      </div>
    </>
  );
}
